/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesValueAddedTaxRouteImport } from './routes/services/value-added-tax'
import { Route as ServicesTrainingRouteImport } from './routes/services/training'
import { Route as ServicesTaxationRouteImport } from './routes/services/taxation'
import { Route as ServicesReconciliationRouteImport } from './routes/services/reconciliation'
import { Route as ServicesReceivershipLiquidationRouteImport } from './routes/services/receivership-liquidation'
import { Route as ServicesManagementConsultancyRouteImport } from './routes/services/management-consultancy'
import { Route as ServicesInvestigationRouteImport } from './routes/services/investigation'
import { Route as ServicesDebtRecoveryRouteImport } from './routes/services/debt-recovery'
import { Route as ServicesCompanyFormationRouteImport } from './routes/services/company-formation'
import { Route as ServicesAuditingRouteImport } from './routes/services/auditing'
import { Route as ServicesAssetVerificationRouteImport } from './routes/services/asset-verification'
import { Route as ServicesAgriculturalExtensionRouteImport } from './routes/services/agricultural-extension'
import { Route as ServicesAccountingRouteImport } from './routes/services/accounting'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesValueAddedTaxRoute = ServicesValueAddedTaxRouteImport.update({
  id: '/services/value-added-tax',
  path: '/services/value-added-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTrainingRoute = ServicesTrainingRouteImport.update({
  id: '/services/training',
  path: '/services/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTaxationRoute = ServicesTaxationRouteImport.update({
  id: '/services/taxation',
  path: '/services/taxation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesReconciliationRoute = ServicesReconciliationRouteImport.update({
  id: '/services/reconciliation',
  path: '/services/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesReceivershipLiquidationRoute =
  ServicesReceivershipLiquidationRouteImport.update({
    id: '/services/receivership-liquidation',
    path: '/services/receivership-liquidation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesManagementConsultancyRoute =
  ServicesManagementConsultancyRouteImport.update({
    id: '/services/management-consultancy',
    path: '/services/management-consultancy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInvestigationRoute = ServicesInvestigationRouteImport.update({
  id: '/services/investigation',
  path: '/services/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDebtRecoveryRoute = ServicesDebtRecoveryRouteImport.update({
  id: '/services/debt-recovery',
  path: '/services/debt-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCompanyFormationRoute =
  ServicesCompanyFormationRouteImport.update({
    id: '/services/company-formation',
    path: '/services/company-formation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAuditingRoute = ServicesAuditingRouteImport.update({
  id: '/services/auditing',
  path: '/services/auditing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAssetVerificationRoute =
  ServicesAssetVerificationRouteImport.update({
    id: '/services/asset-verification',
    path: '/services/asset-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAgriculturalExtensionRoute =
  ServicesAgriculturalExtensionRouteImport.update({
    id: '/services/agricultural-extension',
    path: '/services/agricultural-extension',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAccountingRoute = ServicesAccountingRouteImport.update({
  id: '/services/accounting',
  path: '/services/accounting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/agricultural-extension': typeof ServicesAgriculturalExtensionRoute
  '/services/asset-verification': typeof ServicesAssetVerificationRoute
  '/services/auditing': typeof ServicesAuditingRoute
  '/services/company-formation': typeof ServicesCompanyFormationRoute
  '/services/debt-recovery': typeof ServicesDebtRecoveryRoute
  '/services/investigation': typeof ServicesInvestigationRoute
  '/services/management-consultancy': typeof ServicesManagementConsultancyRoute
  '/services/receivership-liquidation': typeof ServicesReceivershipLiquidationRoute
  '/services/reconciliation': typeof ServicesReconciliationRoute
  '/services/taxation': typeof ServicesTaxationRoute
  '/services/training': typeof ServicesTrainingRoute
  '/services/value-added-tax': typeof ServicesValueAddedTaxRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/agricultural-extension': typeof ServicesAgriculturalExtensionRoute
  '/services/asset-verification': typeof ServicesAssetVerificationRoute
  '/services/auditing': typeof ServicesAuditingRoute
  '/services/company-formation': typeof ServicesCompanyFormationRoute
  '/services/debt-recovery': typeof ServicesDebtRecoveryRoute
  '/services/investigation': typeof ServicesInvestigationRoute
  '/services/management-consultancy': typeof ServicesManagementConsultancyRoute
  '/services/receivership-liquidation': typeof ServicesReceivershipLiquidationRoute
  '/services/reconciliation': typeof ServicesReconciliationRoute
  '/services/taxation': typeof ServicesTaxationRoute
  '/services/training': typeof ServicesTrainingRoute
  '/services/value-added-tax': typeof ServicesValueAddedTaxRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/agricultural-extension': typeof ServicesAgriculturalExtensionRoute
  '/services/asset-verification': typeof ServicesAssetVerificationRoute
  '/services/auditing': typeof ServicesAuditingRoute
  '/services/company-formation': typeof ServicesCompanyFormationRoute
  '/services/debt-recovery': typeof ServicesDebtRecoveryRoute
  '/services/investigation': typeof ServicesInvestigationRoute
  '/services/management-consultancy': typeof ServicesManagementConsultancyRoute
  '/services/receivership-liquidation': typeof ServicesReceivershipLiquidationRoute
  '/services/reconciliation': typeof ServicesReconciliationRoute
  '/services/taxation': typeof ServicesTaxationRoute
  '/services/training': typeof ServicesTrainingRoute
  '/services/value-added-tax': typeof ServicesValueAddedTaxRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/services/accounting'
    | '/services/agricultural-extension'
    | '/services/asset-verification'
    | '/services/auditing'
    | '/services/company-formation'
    | '/services/debt-recovery'
    | '/services/investigation'
    | '/services/management-consultancy'
    | '/services/receivership-liquidation'
    | '/services/reconciliation'
    | '/services/taxation'
    | '/services/training'
    | '/services/value-added-tax'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/services/accounting'
    | '/services/agricultural-extension'
    | '/services/asset-verification'
    | '/services/auditing'
    | '/services/company-formation'
    | '/services/debt-recovery'
    | '/services/investigation'
    | '/services/management-consultancy'
    | '/services/receivership-liquidation'
    | '/services/reconciliation'
    | '/services/taxation'
    | '/services/training'
    | '/services/value-added-tax'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/services/accounting'
    | '/services/agricultural-extension'
    | '/services/asset-verification'
    | '/services/auditing'
    | '/services/company-formation'
    | '/services/debt-recovery'
    | '/services/investigation'
    | '/services/management-consultancy'
    | '/services/receivership-liquidation'
    | '/services/reconciliation'
    | '/services/taxation'
    | '/services/training'
    | '/services/value-added-tax'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesAccountingRoute: typeof ServicesAccountingRoute
  ServicesAgriculturalExtensionRoute: typeof ServicesAgriculturalExtensionRoute
  ServicesAssetVerificationRoute: typeof ServicesAssetVerificationRoute
  ServicesAuditingRoute: typeof ServicesAuditingRoute
  ServicesCompanyFormationRoute: typeof ServicesCompanyFormationRoute
  ServicesDebtRecoveryRoute: typeof ServicesDebtRecoveryRoute
  ServicesInvestigationRoute: typeof ServicesInvestigationRoute
  ServicesManagementConsultancyRoute: typeof ServicesManagementConsultancyRoute
  ServicesReceivershipLiquidationRoute: typeof ServicesReceivershipLiquidationRoute
  ServicesReconciliationRoute: typeof ServicesReconciliationRoute
  ServicesTaxationRoute: typeof ServicesTaxationRoute
  ServicesTrainingRoute: typeof ServicesTrainingRoute
  ServicesValueAddedTaxRoute: typeof ServicesValueAddedTaxRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/value-added-tax': {
      id: '/services/value-added-tax'
      path: '/services/value-added-tax'
      fullPath: '/services/value-added-tax'
      preLoaderRoute: typeof ServicesValueAddedTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/training': {
      id: '/services/training'
      path: '/services/training'
      fullPath: '/services/training'
      preLoaderRoute: typeof ServicesTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/taxation': {
      id: '/services/taxation'
      path: '/services/taxation'
      fullPath: '/services/taxation'
      preLoaderRoute: typeof ServicesTaxationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/reconciliation': {
      id: '/services/reconciliation'
      path: '/services/reconciliation'
      fullPath: '/services/reconciliation'
      preLoaderRoute: typeof ServicesReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/receivership-liquidation': {
      id: '/services/receivership-liquidation'
      path: '/services/receivership-liquidation'
      fullPath: '/services/receivership-liquidation'
      preLoaderRoute: typeof ServicesReceivershipLiquidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/management-consultancy': {
      id: '/services/management-consultancy'
      path: '/services/management-consultancy'
      fullPath: '/services/management-consultancy'
      preLoaderRoute: typeof ServicesManagementConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/investigation': {
      id: '/services/investigation'
      path: '/services/investigation'
      fullPath: '/services/investigation'
      preLoaderRoute: typeof ServicesInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/debt-recovery': {
      id: '/services/debt-recovery'
      path: '/services/debt-recovery'
      fullPath: '/services/debt-recovery'
      preLoaderRoute: typeof ServicesDebtRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/company-formation': {
      id: '/services/company-formation'
      path: '/services/company-formation'
      fullPath: '/services/company-formation'
      preLoaderRoute: typeof ServicesCompanyFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/auditing': {
      id: '/services/auditing'
      path: '/services/auditing'
      fullPath: '/services/auditing'
      preLoaderRoute: typeof ServicesAuditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/asset-verification': {
      id: '/services/asset-verification'
      path: '/services/asset-verification'
      fullPath: '/services/asset-verification'
      preLoaderRoute: typeof ServicesAssetVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/agricultural-extension': {
      id: '/services/agricultural-extension'
      path: '/services/agricultural-extension'
      fullPath: '/services/agricultural-extension'
      preLoaderRoute: typeof ServicesAgriculturalExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/accounting': {
      id: '/services/accounting'
      path: '/services/accounting'
      fullPath: '/services/accounting'
      preLoaderRoute: typeof ServicesAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesAccountingRoute: ServicesAccountingRoute,
  ServicesAgriculturalExtensionRoute: ServicesAgriculturalExtensionRoute,
  ServicesAssetVerificationRoute: ServicesAssetVerificationRoute,
  ServicesAuditingRoute: ServicesAuditingRoute,
  ServicesCompanyFormationRoute: ServicesCompanyFormationRoute,
  ServicesDebtRecoveryRoute: ServicesDebtRecoveryRoute,
  ServicesInvestigationRoute: ServicesInvestigationRoute,
  ServicesManagementConsultancyRoute: ServicesManagementConsultancyRoute,
  ServicesReceivershipLiquidationRoute: ServicesReceivershipLiquidationRoute,
  ServicesReconciliationRoute: ServicesReconciliationRoute,
  ServicesTaxationRoute: ServicesTaxationRoute,
  ServicesTrainingRoute: ServicesTrainingRoute,
  ServicesValueAddedTaxRoute: ServicesValueAddedTaxRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
